# Generated by Django 4.0.4 on 2022-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='tmp_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
