# Generated by Django 4.0.4 on 2022-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeus_app', '0002_novel_tmp_body_alter_novel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
